### ISSUE TITLE
"cordova platform add" fails to restore plugin *randomly*

### ISSUE THREAD

**Issue by AvidanBaruchiN** [apache/cordova-cli#302]
cordova 8.0.0
node 8.11.1
npm 5.6.0

in our build process we call "cordova platform add android" which installs all plugins and the required platform before we build the project.

after i upgraded cordova to version 8.0.0 and all the plugins (and their dependencies) i always get an error when calling the platform add.

the error i get is:

> Failed to restore plugin "cordova-plugin-camera" from config.xml. You might need to try adding it again. Error: Failed to fetch plugin cordova-plugin-camera@4.0.3 via registry.
> Probably this is either a connection problem, or plugin spec is incorrect.
> Check your connection and plugin name/version/URL.
> Failed to get absolute path to installed module

it appears that **changing the order of the plugins causes the same error to a different plugin**!
node_modules is updated with the correct plugins.
installing the plugin manually via "cordova plugin add <plugin name>" pass successfully.

[packageJson.txt](https://github.com/apache/cordova-cli/files/2314985/packageJson.txt)
[configXml.txt](https://github.com/apache/cordova-cli/files/2314988/configXml.txt)

**Comment by AvidanBaruchiN** [comment]
nightly builds are not the solution for us.
we must use stable versions.

BTW what kind of fixes does it include?
and when the next release is gonna be out?

10x.

**Comment by raphinesse** [comment]
@AvidanBaruchiN I'm not asking you to use the nightly build in production, I'm asking you to check if you can reproduce the bug with the nightly build. If not, then there's nothing left to do but wait for the next release.

**Comment by raphinesse** [comment]
Please let us know when you have any more information. Until then, I'm closing this issue.
