### ISSUE TITLE
Use meow?

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-cli#309]
In <https://github.com/apache/cordova-lib/pull/671#discussion_r214034121> @raphinesse mentioned refactoring the CLI using `yargs` or something similar.

I wanted to add a suggestion to take a look at the `meow` package [[1]](https://github.com/sindresorhus/meow) [[2]](https://www.npmjs.com/package/meow) which seems to make CLIs extremely easy to write. I made a quick (dumb) demo in [[3]](https://github.com/brodybits/easy-rm-rf).

[1] <https://github.com/sindresorhus/meow>
[2] <https://www.npmjs.com/package/meow>
[3] <https://github.com/brodybits/easy-rm-rf>

**Comment by raphinesse** [comment]
I remember taking a look and that I felt it was a bit too limited for our needs. Can't exactly remember what it was. Maybe sub-command support? I'll be sure to consider it, should I actually get to the rewrite.

**Comment by brodybits** [comment]
Makes sense. I would favor reporting any such limitations to meow for possible improvement.

**Comment by raphinesse** [comment]
https://github.com/sindresorhus/meow/issues/69

**Comment by raphinesse** [comment]
Given meow's lack of support for sub-commands, I will close this issue.
