### ISSUE TITLE
Defining Content-Security-Policy parameters in order to get violation reports

### ISSUE THREAD

**Issue by TiagoJVO** [apache/cordova-cli#319]
Hello, I'm having some problems defining content security policy on my application due to reports of violations.
I need to have a report each time a csp violation occur. I followed your documentation at [https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-whitelist/#content-security-policy](url)
> On Android and iOS, the network request whitelist (see above) is not able to filter all types of requests (e.g. <video> & WebSockets are not blocked). So, in addition to the whitelist, you should use a Content Security Policy <meta> tag on all of your pages.

But there is a problem, `report-to` and `report-uri` are not supported on `<meta>` tag ([https://w3c.github.io/webappsec-csp/](url).

What am I supposed to do in this case? When an application is already bundled with all `.html` pages and does not communicate with the server?

**Comment by janpio** [comment]
The whitelist plugin lives over at https://github.com/apache/cordova-plugin-whitelist. You might want to open your issue over there (and probably also ask the same thing on StackOverflow, becaues more people will see it there).
