### ISSUE TITLE
Add plugin with private repository, keep reporting cordova error

### ISSUE THREAD

**Issue by zechs424** [apache/cordova-cli#323]
Cordova-cli version : 8.0.0

I am using a private git repo to install my plugin. A type the following command and keep report error:
ionic cordova plugin add git+ssh://<private_repo>

while I install the same plugin using local file system, there is no such error. 
Also if I downgrade my cordova-cli to version 6.5.0. the error has also gone and installed plugin successfully.

Please advise what should I do or check which part of my plugin to resolve problem ?

Error Stack:

node:97726) UnhandledPromiseRejectionWarning: CordovaError: Failed to fetch plugin git+ssh://<private_repo> via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://<private_repo>
npm ERR!
npm ERR! GitLab: The project you were looking for could not be found.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zechs/.npm/_logs/2018-09-13T05_10_18_589Z-debug.log
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:173:37
    at _rejected (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:864:24)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:890:30
    at Promise.when (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:808:41)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:624:44
    at runSingle (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:97726) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:97726) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by raphinesse** [comment]
Please check if the problem persists with `cordova@nightly`. This issue is likely already resolved and the fix due to be released in the next major release.

**Comment by zechs424** [comment]
Yes. Tried nightly version. The problem has gone. Thanks. May I know when will be the next major release comes out ?

**Comment by raphinesse** [comment]
Great to hear that this is resolved for you. I'm sorry to say that I can give you no time frame for the release of the next major, but we are currently working on it. You can follow the progress in https://github.com/apache/cordova/issues/10.
