### ISSUE TITLE
After run ionic cordova prepare, my private repo ionic native plugin has gone

### ISSUE THREAD

**Issue by zechs424** [apache/cordova-cli#324]
Cordova-Cli version : 8.0.0

After I install my ionic native plugin by 
npm install --save git+ssh://<private_repo>

then run "ionic cordova prepare" to initial my android environment.
I found that my  @ionic-native plugin is disappeared in node_modules folder. (the whole folder is deleted)

May I know what is going on or anything I can check ?  Thank in advance.

**Comment by raphinesse** [comment]
Again, could you please verify whether this happens in nightly too?

**Comment by zechs424** [comment]
Yes. It is happened in nightly too.

**Comment by raphinesse** [comment]
You are writing `@ionic-native`. Why the "at" is it a scoped plugin?

Could you please post the output of running `cordova info` followed by `cordova prepare --verbose` both using the nightly version. A minimal test case repo would be helpful too, but that might be hard if you are installing from a private git server.

**Comment by janpio** [comment]
Ionic Native provides wrappers for several Cordova plugins. You install the plugin, then a `@ionic-native/foo` package. 

@zechs424, you should provide a lot more information what you are actually doing: What exactly are you installing - a Cordova plugin or something for Ionic Native? What is your `ionic info` output?

Best provide _all_ commands to reproduce this beginning with `cordova create` or `ionic start` that lead to this failure.

**Comment by zechs424** [comment]
Actually I am making a cordova-plugin for ionic program to call from. I also make ionic-native plugin wrapper for ionic app to call. Just wonder why after I have run "ionic cordova prepare" and the ionic-native plugin wrapper is deleted in nodules_modules folder. And I can't continue to do "ionic cordova build android". It is because the wrapper is missing in node_modules folder

**Comment by janpio** [comment]
> Best provide all commands to reproduce this beginning with cordova create or ionic start that lead to this failure.

**Comment by zechs424** [comment]
ionic Info:
Ionic:

   ionic (Ionic CLI)  : 4.1.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.0.1-nightly.2018.9.13.20af4ecf (cordova-lib@9.0.0-nightly.2018.9.13.87e9f5cd)
   Cordova Platforms     : not available
   Cordova Plugins       : not available

System:

   NodeJS : v8.11.4 (/usr/local/bin/node)
   npm    : 5.6.0
   OS     : macOS High Sierra




Steps to reproduce:
ionic start <new_app>
npm install
ionic cordova plugin add git+ssh://<private_repo>    (add the cordova plugin)
npm install --save <private repo>  (install ionic wrapper)
<check in all the changes to git repository>


Then I do the android build to produce the apk file in another machine
git clone <ionic_source_git_repo>
npm install
ionic cordova prepare


Then the ionic wrapper will disappear in the node_modules folders
It is because when I do "ionic cordova build android", I found the ionic wrapper is missing.

in config.xml and package.json, the ionic wrapper and cordova plugin has entries on both files and point to git+ssh://<private_repo>

**Comment by dpogue** [comment]
I can't be sure if it's the same problem, but I've run into a [similar situation](https://gist.github.com/dpogue/f8bd67888040a06f16d41ec3ee179055) where a custom tool calling `cordova prepare` causes my node_modules folder to get emptied when npm tries to install dependencies that are pointing at git repos. In my case it only happens when I run it on my Jenkins buildmachine, but @raphinesse was able to reproduce it locally. It did not happen when running `cordova prepare` directly with cordova-cli, it only happened when a custom tool make the same call with the same parameters :disappointed: 

I don't know what's causing it and whether it's a cordova bug or an npm bug, but it is on my list of annoying things I want to track down and fix.

**Comment by raphinesse** [comment]
The closest I can do to try and reproduce this issue with the information provided is what I did in https://github.com/apache/cordova-cli/issues/400#issuecomment-482273138. Closing for now.

Please provide a complete reproducible test case using Cordova 9 if we should investigate this further.
