### ISSUE TITLE
Telemetry: Platforms and plugins usage and versions

### ISSUE THREAD

**Issue by janpio** [apache/cordova-cli#330]
One very interesting thing to know would be the platforms and plugins being used/installed (including version). This would enable much better decisions on how to handle platform and plugin updates, but also what users are still using out there and thus has to be supported.

It would enable us to build similar graphs to https://datastudio.google.com/reporting/0B-Ja5cNOX_XLTElHdWd4V2NUem8/page/jfJF for platforms, individual versions of platforms, plugins in general, or versions of specific plugins (e.g. core plugins).

**Comment by brodybits** [comment]
Would this be a part of Cordova CLI telemetry or something else?

**Comment by dpogue** [comment]
One caution here is that lots of companies have private in-house plugins. We might want to only track install stats for plugins that are publicly available on npm (but I'm not sure how we'd do that)

**Comment by brodybits** [comment]
I had thought we would only want to track plugins maintained by Cordova itself.

Alternative may be to check the download statistics available on npm and GitHub.

**Comment by janpio** [comment]
> Would this be a part of Cordova CLI telemetry or something else?

Yes of course, additionally to the data that is already tracked.

> One caution here is that lots of companies have private in-house plugins. We might want to only track install stats for plugins that are publicly available on npm (but I'm not sure how we'd do that)

Full agreement. Maybe just a list of defined core plugins as @brodybits suggested. Whatever is actually interesting for us.

> Alternative may be to check the download statistics available on npm and GitHub.

Yes, that might be a workaround that already works.

**Comment by janpio** [comment]
Turns out the download statistics from NPM are only for the plugin in general, not for the individual versions :( They have the data, but no API to access it.

**Comment by dpogue** [comment]
Telemetry has been removed, so closing this issue
