### ISSUE TITLE
Set Default Apps Map

### ISSUE THREAD

**Issue by sangle1996** [apache/cordova-cli#336]
HI there, I have a link that direct to google map 
href="geo:0,0?q=201%2BMassachusetts%2BAvenue,+Lexington,+MA,+02420".
since im install waze map it ask to use between two app. I want to set Google Map by default(in code not 
 in android platform). Thank..

**Comment by raphinesse** [comment]
This is not a support forum. Please ask such questions on stackoverflow or in our slack.
