### ISSUE TITLE
AppVeyor CI no longer run on this repository

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-cli#345]
as discussed in PR #340

**Comment by janpio** [comment]
Seems the tests are run - but not reported to Github:
https://ci.appveyor.com/project/ApacheSoftwareFoundation/cordova-cli/history

![image](https://user-images.githubusercontent.com/183673/46137698-76205900-c24a-11e8-8bde-492562261193.png)

**Comment by raphinesse** [comment]
I noticed the same thin in cordova-common yesterday. Thought it was a hiccup then...

**Comment by raphinesse** [comment]
Currently AppVeyor works as expected
