### ISSUE TITLE
Add plugin each platform

### ISSUE THREAD

**Issue by MnGuii** [apache/cordova-cli#350]
It's possible to add different plugins each platform in the same config.xml?
I tried this but not fetched the plugin while is compile.

```
<platform name="ios">
	<plugin name="hu.dpal.phonegap.plugins.spinnerdialog" spec="https://github.com/Sharinglabs/SpinnerDialog.git#007f0c0"/>
</platform>

<platform name="android">
	<plugin name="cordova-plugin-spinner-dialog" spec="https://github.com/Paldom/SpinnerDialog.git#a9276f5" />
</platform>
```

Any help?

**Comment by dpogue** [comment]
I don't think this is supported. We're moving to a system where plugins are listed in package.json, so all the same plugins will be installed for all platforms.

**Comment by raphinesse** [comment]
Sorry, but there's nothing more we can do here.
