### ISSUE TITLE
Showing phonegap 8.0 but have seen news about 8.1.1

### ISSUE THREAD

**Issue by FreddyCrugger** [apache/cordova-cli#351]
Hello,

I am a bit confused, I saw this article here:
https://cordova.apache.org/news/2018/09/27/cordova-cli-8.1.1.html

But the git repo when using the @latest build gives me version 8.0.0

Any idea why please?

Thank you,

**Comment by janpio** [comment]
What git repo are you talking about?
How is this related to Phonegap?

**Comment by FreddyCrugger** [comment]
My mistake I thought cordova and phonegap were pretty much the same thing but it looks like cordova has less options than Phonegap.

**Comment by janpio** [comment]
It's more like that Phonegap uses Cordova internally and adds some stuff on top.

**Comment by FreddyCrugger** [comment]
Yes, got it, thanks
