### ISSUE TITLE
Failure to restore local plugins from config.xml

### ISSUE THREAD

**Issue by janpio** [apache/cordova-cli#387]
See: https://ionic.zendesk.com/hc/en-us/articles/360009519314-Managing-local-cordova-plugins

**Comment by raphinesse** [comment]
It's sad that people seem to have to resort to such ugly workarounds. But there is no reproducible test case. How should we act upon this?

**Comment by dpogue** [comment]
As far as I can tell, this isn't a supported workflow. Plugins are like platforms: meant to be treated as build artifacts and not committed to the repo.

This is claimed as a workaround for private plugins, but pointing to a git repo or a known filesystem location is a much better alternative.

**Comment by raphinesse** [comment]
Ah, now I got the "problem". I agree 💯% @dpogue. Closing
