### ISSUE TITLE
Modifying different attributes of same AndroidManifest.xml element in config.xml and plugin.xml results in conflict

### ISSUE THREAD

**Issue by lasselaakkonen** [apache/cordova-cli#389]
Using `cordova@8.1.2`, `cordova-android@7.1.4`.

For example if `config.xml` contains:
```
<edit-config file="AndroidManifest.xml" target="/manifest/application" mode="merge">
  <application android:largeHeap="true" />
</edit-config>
```

And `plugin.xml` contains:
```
<edit-config file="AndroidManifest.xml" target="/manifest/application" mode="merge">
  <application android:usesCleartextTraffic="true" />
</edit-config>
```

Adding the plugin will fail with `<edit-config> changes in this plugin conflicts with <edit-config> changes in config.xml`.

## Steps to reproduce

Using `cordova@8.1.2`.

```
git clone https://github.com/lasselaakkonen/cordova-plugineditconfigissue
cd cordova-plugineditconfigissue
cordova platform add android
cordova plugin add cleartextplugin
```

**Comment by janpio** [comment]
I don't know nearly enough about this functionality to assess if this is a bug, undefined or even wanted behavior. 

A short read of the docs shows https://cordova.apache.org/docs/en/8.x/plugin_ref/spec.html#managing-edit-config-conflicts which introduces `--force`, although in the context of 2 conflicting plugins - not `config.xml vs plugin.xml`. What happens if you use that?

**Comment by guylando** [comment]
+1 
Encountered this too.
And the described scenario should not bring the need of using force flag.

**Comment by raphinesse** [comment]
Looks like a bug to me. Error is thrown here: https://github.com/apache/cordova-common/blob/193c9f3e2bf003292d12782f2d182a08c1b562b8/src/ConfigChanges/ConfigChanges.js#L135

**Comment by dpogue** [comment]
Not exactly the same bug, but in a related spot of the code: It's on my to-do list next week to investigate https://github.com/apache/cordova-android/issues/704 where `edit-config` directives seem to get ignored with no error message
