### ISSUE TITLE
Cordova fails if space is present in path

### ISSUE THREAD

**Issue by realivanjx** [apache/cordova-cli#391]
Hi,

I have been struggling by this problem for hours. It seems that space in my windows user name causes this problem to happen. Im not really sure if this problem is android specific or not so i posted this problem here instead. Please see the screenshots i have attached below to understand my problem:

Normal `adb devices` command result:
![screenshot_47](https://user-images.githubusercontent.com/12814796/50065362-bd363e80-01e8-11e9-8263-cde891a36ffa.png)

`cordova run android` initial result:
![screenshot_48](https://user-images.githubusercontent.com/12814796/50065376-cfb07800-01e8-11e9-8d43-bf6ef071a809.png)

`cordova run android` error message:
![screenshot_49](https://user-images.githubusercontent.com/12814796/50065384-d939e000-01e8-11e9-9073-d871427a1b09.png)

I think by just adding `"` characters between the adb path should fix this problem but i cant do that with cordova cli. Please help.

**Comment by janpio** [comment]
What is your indication that the command is run in a wrong way?

The command being executed is part of `cordova-android`: https://github.com/apache/cordova-android/blob/23b24491c3e2ad5721a2813ec08f80985eca5e64/bin/templates/cordova/lib/build.js#L162-L166 So you should probably create an issue over there: https://github.com/apache/cordova-android/issues/new
