### ISSUE TITLE
Repos moved to Github

### ISSUE THREAD

**Issue by monomelodies** [apache/cordova-cli#398]
Previously, platforms were hosted by apache.org under https://git-wip-us.apache.org/repos/asf?p=cordova-PLATFORM.git. Cordova@nightly has updated these to use Github repos, but this change is not reflected in the latest stable release (8.1.2 / lib@8.1.1). The old repos have since been removed, meaning I cannot install anything.

Manually doctoring the URLs in platformsConfig.json does not seem to work, the CLI keeps telling me no suitable platform can be found. Cordova@nightly also fails to install any platform (I had it working for cordova-browser yesterday evening, now no such luck).

Am I doing something wrong or did this simply break and should I wait for a new release that fixes it? If so, any ideas on a time path? Cordova is now effectively unusable for me.

**Comment by dpogue** [comment]
Unless you're specifically telling cordova-cli to install from git, it should be trying to installed the published versions from npm (including for nightly versions).

**Comment by monomelodies** [comment]
> Unless you're specifically telling cordova-cli to install from git, it should be trying to installed the published versions from npm (including for nightly versions).

Finally found some time to dig into this, and thought I'd share what I
found (if only for future reference). The tl;dr: it wasn't Cordova at
all. 

Turns out my entire NPM install had gone FUBAR (no idea how _that_
happened). In `/usr/local/lib/node_modules` was a symlink to an `npm`
package, that linked to... itself. That explains the ELOOP error. Oddly
enough "normal" NPM usage wasn't affected AFAICT, but perhaps the
executable is self-contained enough for this not to be a problem. I
reinstalled Cordova prior to finding the solution mentioned below, and
that worked just fine. 

Anyway, the solution: 

1. Remove nodejs completely (`sudo apt-get remove nodejs`)
2. Manually remove the stale symlink (`sudo unlink
/usr/local/lib/node_modules/npm`)
3. Reinstall nodejs (`sudo apt-get install nodejs`)
4. Make sture we're at the latest version again (`sudo n stable`)
5. Update npm to latest version (`sudo npm i -g npm`) 

...and all was well with `cordova platform` again!

**Comment by erisu** [comment]
@monomelodies, Thank you for the update, I will go ahead and close out this ticket as it has been resolved.
