### ISSUE TITLE
Is telemetry synchronous?

### ISSUE THREAD

**Issue by janpio** [apache/cordova-cli#405]
I noticed some unexpected slowness in the CLI. Is it possible that telemetry calls are sync?

See the following output:

```
E:\Projects\throwaway\x4wTest (master -> origin) (helloworld@1.0.0)
λ cordova telemetry on
Thanks for opting into telemetry to help us improve cordova.

E:\Projects\throwaway\x4wTest (master -> origin) (helloworld@1.0.0)
λ cordova -v | gnomon
   2.1843s   8.1.2 (cordova-lib@8.1.1)
   0.0016s

     Total   2.1887s

E:\Projects\throwaway\x4wTest (master -> origin) (helloworld@1.0.0)
λ cordova telemetry off
You have been opted out of telemetry. To change this, run: cordova telemetry on.

E:\Projects\throwaway\x4wTest (master -> origin) (helloworld@1.0.0)
λ cordova -v | gnomon
   1.2091s   8.1.2 (cordova-lib@8.1.1)
   0.0017s

     Total   1.2138s
```

(`gnomon` is the tool that measures the time it takes for each line of the output to appear, install via `npm install -g gnomon`.)

---

```
λ cordova -v
8.1.2 (cordova-lib@8.1.1)
```

**Comment by raphinesse** [comment]
The tracking should run asynchronously in a new process: https://github.com/yeoman/insight/issues/34

**Comment by raphinesse** [comment]
Well, the question in the title is answered. Should we close this or rename it to something more actionable?

**Comment by janpio** [comment]
Why is the CLI slower when telemtry is enabled then? 
Or does it still wait for that process to finish before returning to the console?

**Comment by raphinesse** [comment]
I also experience the difference. 1 s without telemetry vs 2 s with. I don't see any offenders in a `0x` flame graph which _does_ suggests that a child process is responsible for the delay. However, the child process should not be waited upon, the way it is handled:
https://github.com/yeoman/insight/blob/cb32c1a043c54d50ef1aff04c7a70f761bcb8035/lib/index.js#L85-L88

So it's maybe just the overhead of spawning a new Node.js process and doing the IPC :man_shrugging: 

I think the only thing we could do is to create a minimal example that showcases this and report it at the `inquirer` repo.
