### ISSUE TITLE
Telemetry: Main CLI parameters/flags

### ISSUE THREAD

**Issue by janpio** [apache/cordova-cli#407]
Currently only the command, subcommand and execution status are tracked. 

This unfortunately looses a lot of important information about the parameter usage: `--device` vs `--emulator`, `--debug` vs. `--release` in the build process for example.

It would be neat if we could somehow also track the most used parameters/flags.

Important to note that the individual values of some params (build options for example) are of no interest at all to us, we could just learn quite a lot by being able to understand what code paths are actually used.

**Comment by dpogue** [comment]
Telemetry has been removed, so closing this issue
