### ISSUE TITLE
cordova-ios <podspec not working due to cordova-common < 3.0.0

### ISSUE THREAD

**Issue by mzealey** [apache/cordova-cli#411]
# Bug Report

### What is expected to happen?

In a plugin.xml file, `<podspec>` sections should be supported correctly since cordova-ios 5

### What does actually happen?

It is ignored

## Information

The `plugin.getPodSpecs` function call was only added at cordova-common 3.0.0, but current cordova only uses 2.2.0. Can you please fix or advise how to force a newer version of cordova-common to be used by the cordova npm module?

**Comment by erisu** [comment]
Hi @mzealey, Cordova CLI 9 has been released and uses `cordova-common@^3.1.0`.

Can you try using Cordova CLI 9? This should resolve your issue.

If Cordova CLI 8.x is required, I believe the next `cordova-ios` patch (`5.0.1`) will have this resolved. I think this PR resolved it as well: https://github.com/apache/cordova-ios/pull/573
