### ISSUE TITLE
Possibility of preventing certain files or folders from reloading the page during `phonegap serve`

### ISSUE THREAD

**Issue by Hissvard** [apache/cordova-cli#413]
# Feature Request

## Motivation Behind Feature
An example:
* `scss --watch /scss/file.scss:/../css/file.css`
* `phonegap serve`
* Open localhost:3000 in your browser

Now, every time the scss file is saved, the browser reloads the page *twice*: When the scss file is changed by the editor and when the file is compiled to css. Waiting for the page to reload twice at every change is a pretty slow way to develop.

## Feature Description
It would be perfect if one could issue something like
```
phonegap serve --ignore /scss/
```
or 
```
phonegap serve --unwatch /scss/
```
to prevent certain files or folders from reloading the page when changed.

## Alternatives or Workarounds
I haven't been able to come up with an alternative other than putting the `scss` folder outside of the project so it's not watched for changes. That's... Not too elegant.

**Comment by janpio** [comment]
You should create an issue with the Phonegap CLI repository then: https://github.com/phonegap/phonegap-cli
