### ISSUE TITLE
Crash error in 9.0.0: "Cannot read property 'reject' of undefined"

### ISSUE THREAD

**Issue by Annelies1** [apache/cordova-cli#415]
# Bug Report

## Problem
When I do "cordova build ios"  or "cordova buid android" I get the error "Cannot read property 'reject' of undefined".
When I downgrade to version 8.1.2. it works fine

### What is expected to happen?
Expect building ios or android. Nothing happens now.

### What does actually happen?
I get the error "Cannot read property 'reject' of undefined" instead.

## Information

After upgrading to 9.0.0 I got the above issue. When I downgrade to version 8.1.2. it works fine again.

With --verbose I get this:

No scripts found for hook "before_build".
Executing script found in plugin cordova-custom-config for hook "before_prepare": plugins/cordova-custom-config/hooks/restoreBackups.js
Cannot read property 'reject' of undefined
TypeError: Cannot read property 'reject' of undefined
   at module.exports (/Users/dbxaee/kvk/kvk-connect-client-mobile-devices/plugins/cordova-custom-config/hooks/restoreBackups.js:134:18)
   at runScriptViaModuleLoader (/Users/dbxaee/.config/yarn/global/node_modules/cordova-lib/src/hooks/HooksRunner.js:181:32)
   at runScript (/Users/dbxaee/.config/yarn/global/node_modules/cordova-lib/src/hooks/HooksRunner.js:157:16)
   at /Users/dbxaee/.config/yarn/global/node_modules/cordova-lib/src/hooks/HooksRunner.js:125:20
   at process.runNextTicks [as _tickCallback] (internal/process/next_tick.js:47:5)
   at Function.Module.runMain (internal/modules/cjs/loader.js:804:11)
   at internal/main/run_main_module.js:21:11

### Command or Code

I cannot put the client's code here. Haven't got the time to reproduce it for you on empty project.

### Environment, Platform, Device

In the terminal of Mac OS Sierra 10.13.6

### Version information
Cordova 9.0.0

## Checklist

- [ x] I searched for existing GitHub issues
- [ x] I updated all Cordova tooling to most recent version
- [ x] I included all the necessary information above

**Comment by dpogue** [comment]
Can you run `cordova build ios --verbose` and attach the terminal output? We can't even start to investigate without seeing the full error message

**Comment by Annelies1** [comment]
I added it now

**Comment by Annelies1** [comment]
This is the restoreBackups.js file:

`#!/usr/bin/env node

/**********
 * Globals
 **********/
var TAG = "cordova-custom-config";
var SCRIPT_NAME = "restoreBackups.js";

// Pre-existing Cordova npm modules
var deferral, path, cwd;

// Npm dependencies
var logger,
    fs,
    _,
    fileUtils;

// Other globals
var hooksPath;

var restoreBackups = (function(){

    /**********************
     * Internal properties
     *********************/
    var restoreBackups = {}, context, projectName, logFn, settings;

    var PLATFORM_CONFIG_FILES = {
        "ios":{
            "{projectName}-Info.plist": "{projectName}/{projectName}-Info.plist",
            "project.pbxproj": "{projectName}.xcodeproj/project.pbxproj",
            "build.xcconfig": "cordova/build.xcconfig",
            "build-extras.xcconfig": "cordova/build-extras.xcconfig",
            "build-debug.xcconfig": "cordova/build-debug.xcconfig",
            "build-release.xcconfig": "cordova/build-release.xcconfig",
            "Entitlements-Release.plist": "{projectName}/Entitlements-Release.plist",
            "Entitlements-Debug.plist": "{projectName}/Entitlements-Debug.plist"
        },
        "android":{
            "AndroidManifest.xml": "AndroidManifest.xml"
        }
    };

    /*********************
     * Internal functions
     *********************/

    function restorePlatformBackups(platform){
        var configFiles = PLATFORM_CONFIG_FILES[platform],
            backupFile, backupFileName, backupFilePath, backupFileExists, targetFilePath;

        logger.verbose("Checking to see if there are backups to restore...");
        for(backupFile in configFiles){
            backupFileName = parseProjectName(backupFile);
            backupFilePath = path.join(cwd, 'plugins', context.opts.plugin.id, "backup", platform, backupFileName);
            backupFileExists = fileUtils.fileExists(backupFilePath);
            if(backupFileExists){
                targetFilePath = path.join(cwd, 'platforms', platform, parseProjectName(configFiles[backupFile]));
                fileUtils.copySync(backupFilePath, targetFilePath);
                logFn("Restored backup of '"+backupFileName+"' to :"+targetFilePath);
            }
        }
    }

    function parseProjectName(fileName){
        return fileName.replace(/{(projectName)}/g, projectName);
    }

    // Script operations are complete, so resolve deferred promises
    function complete(){
        deferral.resolve();
    }

    /*************
     * Public API
     *************/
    restoreBackups.loadDependencies = function(ctx){
        fs = require('fs'),
        _ = require('lodash'),
        fileUtils = require(path.resolve(hooksPath, "fileUtils.js"))(ctx);
        logger.verbose("Loaded module dependencies");
    };

    restoreBackups.init = function(ctx){
        context = ctx;

        projectName = fileUtils.getProjectName();
        logFn = context.hook === "before_plugin_uninstall" ? logger.log : logger.verbose;

        settings = fileUtils.getSettings();
        if(typeof(settings.autorestore) === "undefined" || settings.autorestore === "false"){
            logger.log("Skipping auto-restore of config file backup(s)");
            complete();
            return;
        }

        // go through each of the platform directories
        var platforms = _.filter(fs.readdirSync('platforms'), function (file) {
            return fs.statSync(path.resolve('platforms', file)).isDirectory();
        });
        _.each(platforms, function (platform, index) {
            platform = platform.trim().toLowerCase();
            try{
                restorePlatformBackups(platform);
                if(index === platforms.length - 1){
                    logger.verbose("Finished restoring backups");
                    complete();
                }
            }catch(e){
                var msg = "Error restoring backups for platform '"+platform+"': "+ e.message;
                logger.error(msg);
                if(settings.stoponerror){
                    deferral.reject(TAG + ": " +msg);
                }
            }
        });
    };

    return restoreBackups;
})();

module.exports = function(ctx) {
    try{
        deferral = require('q').defer();
        path = require('path');
        cwd = path.resolve();

        hooksPath = path.resolve(ctx.opts.projectRoot, "plugins", ctx.opts.plugin.id, "hooks");
        logger = require(path.resolve(hooksPath, "logger.js"))(ctx);

        restoreBackups.loadDependencies(ctx);
    }catch(e){
        e.message = TAG + ": Error loading dependencies for "+SCRIPT_NAME+" - ensure the plugin has been installed via cordova-fetch or run 'npm install cordova-custom-config': "+e.message;
        if(typeof deferral !== "undefined"){
            deferral.reject(e.message);
            return deferral.promise;
        }
        throw e;
    }

    try{
        logger.verbose("Running " + SCRIPT_NAME);
        restoreBackups.init(ctx);
    }catch(e){
        var msg = TAG + ": Error running "+SCRIPT_NAME+": "+e.message;
        deferral.reject(msg);
    }

    return deferral.promise;
};
`

**Comment by dpogue** [comment]
This is a problem with the cordova-custom-config plugin. It looks like [been fixed](https://github.com/dpa99c/cordova-custom-config/issues/152) in `cordova-custom-config@5.1.0`.

If you're still encountering errors, please try reporting the problem on the cordova-custom-config plugin repo.

**Comment by Annelies1** [comment]
thanks @dpogue  for helping me. I will go to that repo for further info.
