### ISSUE TITLE
cordova config ls returns Error: ENOENT on clean install

### ISSUE THREAD

**Issue by ltm** [apache/cordova-cli#418]
# Bug Report

## Problem

The configstore dependency was upgraded from 2.1.0 to 4.0.0 in #312. However, as of [v4.0.0](https://github.com/yeoman/configstore/releases/tag/v4.0.0) configstore no longer creates a configuration file when a config is read (yeoman/configstore#57). This causes `cordova config ls` to return `Error: ENOENT` if `cordova-config.json` is missing (e.g. on a clean install).

### What is expected to happen?

The command shouldn't return an error (behavior of 8.1.2):

```
$ rm ~/.config/configstore/cordova-config.json
$ cordova config ls
$
```

### What does actually happen?

The command returns `Error: ENOENT`:

```
$ rm ~/.config/configstore/cordova-config.json
$ cordova config ls
Error: ENOENT: no such file or directory, open '/Users/ltm/.config/configstore/cordova-config.json'
$
```

### Command or Code

```
$ npm install -g cordova@latest
$ rm ~/.config/configstore/cordova-config.json
$ cordova config ls
```

### Environment, Platform, Device

```
$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.14.4
BuildVersion:	18E226
```

### Version information

```
$ cordova --version
9.0.0 (cordova-lib@9.0.1)
```

## Checklist

- [X] I searched for existing GitHub issues
- [X] I updated all Cordova tooling to most recent version
- [X] I included all the necessary information above

**Comment by mobileben** [comment]
@Arxi Unfortunately no. Never figured it out, so I am just ignoring it.

**Comment by Arxi** [comment]
@mobileben seems like manually creating the file `.config/configstore/cordova-config.json` with content `{}` suppresses the error.

**Comment by raphinesse** [comment]
The issue has been fixed, but there hasn't been a release with the fix yet. That's why you still see this.
