### ISSUE TITLE
Remove desktop.ini files on windows 10 before build or run

### ISSUE THREAD

**Issue by leobaccili** [apache/cordova-cli#431]
# Feature Request

## Motivation Behind Feature
Most users on Windows 10 have problems on build with de "desktop.ini" files.

## Feature Description
Running this command before build or run keep the process more easy
`del /S /Q /A:H desktop.ini`

## Alternatives or Workarounds
execute this command by yourself, like this
del /S /Q /A:H desktop.ini & cordova run android

**Comment by janpio** [comment]
> Most users on Windows 10 have problems on build with de "desktop.ini" files.

I am a Windows 10 user and don't really know what you mean by that. Can you elaborate?

**Comment by leobaccili** [comment]
The desktop.ini file is a hidden file used to store information about the arrangement of a Windows folder. Essentially, if the layout or settings for a folder are changed, a desktop.ini file is automatically generated to save those changes.

When i install a plugin or add a platform, many files are generated automatically. When i execute a run or build command, the cli return error indicating a problem with this files.

**Comment by janpio** [comment]
Ok, never noticed that here.

What error do you get because these files exist?

**Comment by nyambol** [comment]
This seems to be a known issue when storing data on [Google Drive](https://iamalsojohn.wordpress.com/2018/04/18/git-google-drive-and-bad-references/). I've been having it, myself. I moved that repo off the g drive.

**Comment by leobaccili** [comment]
Jesus, i'm too late. Like @nyambol says, these errors occurs because the Google Drive, changing the storing to another place resolve this issues. Thanks and sorry for a too late answer.
