### ISSUE TITLE
Compress the main.js file to make it smaller

### ISSUE THREAD

**Issue by longting** [apache/cordova-cli#444]
# Feature Request

## Motivation Behind Feature
Build our product , Compress the main.js file to make it smaller, reduce the time of network transmission. Main.js is really too big.

## Feature Description
like `https://ionicframework.com/docs/cli/commands/build` ,add  `--prod` common options
execute `ionic cordova build browser --prod` 
It turned out to be a 5M JS file, now only 500K.

## Alternatives or Workarounds
like `https://ionicframework.com/docs/cli/commands/build` ,add cordova common options .
I am looking forward to cordova doing better.

**Comment by dpogue** [comment]
Cordova's job is *packaging* your code for mobile distribution, not changing your code in any way.

Tools like uglify-js and terser can be used as part of your build process to minify files before they are packaged by Cordova.
