### ISSUE TITLE
Why resources folder not getting created?

### ISSUE THREAD

**Issue by IsaacHub** [apache/cordova-cli#450]
I have installed the latest CLI v9

I have created a new cordova project using `cordova create hello com.example.hello HelloWorld`, and all folders were created except `resources` folder. **Is this intended or a bug?** 

I thought I will get default icons and splash screens of cordova logo, as we got in older versions inside `res` folder.

I had to create an ionic project separately and integrated cordova using `ionic integrations enable cordova` to just copy over `resources` folder.

**Comment by erisu** [comment]
@IsaacHub https://github.com/apache/cordova/issues/90#issuecomment-477670698
