### ISSUE TITLE
When creating a Cordova project, if the domain name has a number up front, this generates an error

### ISSUE THREAD

**Issue by mobileben** [apache/cordova-cli#461]
# Bug Report

## Problem
Trying to create a project where the domain starts with a number such as `com.123abc.test` will generate an error.

For example:

```
cordova create test com.123abc.com
```

Results in

> App id contains a reserved word, or is not a valid identifier.
### What is expected to happen?

New project should be created

### What does actually happen?

Cannot create the project and instead the following message is output:

> App id contains a reserved word, or is not a valid identifier.

Note that my domain name does start with a digit and I have released products on iOS using the reverse domain name for the app which includes the leading digit. I've never had an issue and I released my first item to the store in 2009. 

## Information
This post probably sums it up:

https://serverfault.com/questions/638260/is-it-valid-for-a-hostname-to-start-with-a-digit

It is valid to have a leading digit on the domain. Cordova treats it as illegal. I have tested the removing leading digits will allow it to work.

### Command or Code
```
cordova create test com.123abc.com
```

### Environment, Platform, Device

Mac OSX 10.14.16

### Version information

Cordova CLI
9.0.0 (cordova-lib@9.0.1)

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by mobileben** [comment]
Note I looked at the code. The issue is that `valid-identifier` explicitly rejects any portion that starts with a number. 

https://github.com/purplecabbage/valid-identifier#readme

That particular library is for 

>simple node module for validating identifiers, package names, and namespaces ( java + C# )

However documentation (https://cordova.apache.org/docs/en/2.9.0/guide/cli/index.html) states 

>The other two arguments are optional: the com.example.hello argument provides your project with a reverse-domain-style identifier

It seems to me if the expectation is that if the argument is passed is to be reverse-domain-style-identifier, then `valid-identifier` is an inappropriate package to use to validate the id.

**Comment by dpogue** [comment]
The problem is that on Android (for example), we turn that ID into a Java package name. `com.123abc.com` is not a valid Java package name, so we reject it.

**Comment by mobileben** [comment]
No worries. I created a few projects to see where it was adding the name. I can always add it post, I think. I assume at some point I'll be able to properly identify the bundle id and not have it subject to `valid-identifier`. 

Documentation is misleading then, indicating reverse-domain-style identifier.

Oh curious, I've been using Webpack for a Typescript project I want to move to mobile. It has an existing package.json. Can I just use that? Or is it more recommended to just use the base Cordova project and add what I need into it?

I'll close this.
