### ISSUE TITLE
Ionic disables Cordova telemetry

### ISSUE THREAD

**Issue by michaelpeterlee** [apache/cordova-cli#462]
### Issue Type
- [x] Support Question

## Description
Just a friendly note that when using the latest Ionic cli on OSX, the terminal advises: "You have been opted out of telemetry. To change this, run: cordova telemetry on." You may like to get Ionic project to fix this so you get telemetry. When we run `cordova telemetry on` that completes successfully, however the Ionic command still trips the warning.

## Information
`cordova plugin add cordova-plugin-sqlite-2` does not trip the warning

### Command or Code
`ionic cordova plugin add cordova-plugin-sqlite-2` trips the warning

### Environment, Platform, Device
Latest OSX, Ionic and Cordova packages

**Comment by erisu** [comment]
This sounds like a bug with Ionic and not Cordova. It would be better if you report this to Ionic instead. Telemetry works as expected with Cordova CLI.

**Comment by michaelpeterlee** [comment]
This is just an advisory to let you know you're missing out on telemetry by default from those folks. Feel free to close from here.

**Comment by raphinesse** [comment]
@michaelpeterlee Thanks for bringing this to our attention. Much appreciated.
