### ISSUE TITLE
`platform add` should save exact version that was written in command

### ISSUE THREAD

**Issue by WuglyakBolgoink** [apache/cordova-cli#465]
# Bug Report

## Problem

I try to install specific platform version, but in `config.xml` this version will be saved with tilde `~x.x.x`

### What is expected to happen?

It will be maybe great, if cordova-cli can use `--exact` attribute like in `npm`.

Add Android platform:
```bash
cordova platform add android@8.1.0 --save
```

Should be in `config.xml`

```xml
 <engine name="android" spec="8.1.0" />
```

### What does actually happen?

Add Android platform:

```bash
cordova platform add android@8.1.0 --save
```

What I have now in `config.xml`

```xml
 <engine name="android" spec="~8.1.0" />
```

## Information

- Cordova version: 8.1.1

### Environment, Platform, Device

- macOS

**Comment by jcesarmobile** [comment]
cordova uses npm to install the platforms and plugins, so it will use whatever you have configured as save-prefix
type `npm config get save-prefix` to see your actual value
type `npm config set save-prefix=""` if you don't want platforms or plugins being saved with `~` or `^`.

Also, cordova  accept the `--save-exact` param to save the exact version

**Comment by WuglyakBolgoink** [comment]
> Also, cordova accept the `--save-exact` param to save the exact version

not always...
