### ISSUE TITLE
'cordova run android' does not deploy the app to emulator

### ISSUE THREAD

**Issue by diaconubogdan** [apache/cordova-cli#466]
# Bug Report

## Problem

'cordova run android' doesn't deploy the app to the emulator. It just gets to a point that it loops over and over

### What is expected to happen?

It should deploy and launch the app on the emulator

### What does actually happen?

The output below is what I get using the --verbose option.

## Information

`Checking Java JDK and Android SDK versions  

ANDROID_SDK_ROOT=C:\Users\xxx\AppData\Local\Android\Sdk (recommended setting)  
ANDROID_HOME=C:\Users\xxx\AppData\Local\Android\Sdk (DEPRECATED)  
Running command: adb devices  
Command finished with error code 0: adb devices  
No target specified and no devices found, deploying to emulator  
Running command: adb devices  
Command finished with error code 0: adb devices  
Running command: adb devices  
Command finished with error code 0: adb devices  
Running adb shell command "cat /proc/cpuinfo" on target emulator-5554...  
Running command: adb -s emulator-5554 shell cat /proc/cpuinfo  
Command finished with error code 0: adb -s,emulator-5554,shell,cat,/proc/cpuinfo  
Running adb shell command "ps" on target emulator-5554...  
Running command: adb -s emulator-5554 shell ps  
Command finished with error code 0: adb -s,emulator-5554,shell,ps  
.Running adb shell command "ps" on target emulator-5554...   
Running command: adb -s emulator-5554 shell ps  
Command finished with error code 0: adb -s,emulator-5554,shell,ps  
.Running adb shell command "ps" on target emulator-5554...  
Running command: adb -s emulator-5554 shell ps  
Command finished with error code 0: adb -s,emulator-5554,shell,ps  
.Running adb shell command "ps" on target emulator-5554...  
Running command: adb -s emulator-5554 shell ps  
Command finished with error code 0: adb -s,emulator-5554,shell,ps  
.Running adb shell command "ps" on target emulator-5554...  
Running command: adb -s emulator-5554 shell ps  
Command finished with error code 0: adb -s,emulator-5554,shell,ps`  

As you can see, it is just looping and not doing anything.  
The same project runs just fine on another machine.
It works like it should when I import the platforms/android folder to Android Studio and run the project.
Tried 'adb logcat', doesn't show anything.

### Command or Code

cordova run android --verbose

### Environment, Platform, Device

  OS: win32
  Node: v10.14.2
  npm: 6.5.0
  Java JDK: installed 1.8.0
  Android SDK: installed true
  Android target: installed android-29,android-28,android-27,android-26
  Gradle: installed C:\Gradle\bin\gradle
  Cordova; 9.0.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
Please do `cordova platform list` and also provide the `cordova-android` version you are running. Thanks.

**Comment by diaconubogdan** [comment]
Wow, that was fast.
cordova platform list:
`Installed platforms:  

  android 8.1.0  
Available platforms:  

  browser ^6.0.0  
  electron ^1.0.0  
  ios ^5.0.0  
  osx ^5.0.0  
  windows ^7.0.0`
Running on cordova-android@8.1.0.

**Comment by breautek** [comment]
I've ran this without the emulator started and seeing you're behavior. If I omit the `--verbose` flag, then the last thing that prints out for me is:

```terminal
No emulator specified, defaulting to Nexus_5X_API_28_x86
Waiting for emulator to start...
PANIC: Missing emulator engine program for 'x86' CPU.
```

**Comment by diaconubogdan** [comment]
The emulator is already started and it detects it, it gets the id 'emulator-5554', which is correct.

**Comment by breautek** [comment]
hmm strange. For me `cordova` command does work if I start the emulator first.

What's the output of `adb devices -l`?

**Comment by diaconubogdan** [comment]
```
List of devices attached  

emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86 features:abb,cmd,shell_v2,abb_exec,stat_v2,fixed_push_mkdir,apex,fixed_push_symlink_timestamp
```

**Comment by diaconubogdan** [comment]
OK, it looks like I already had a version of Android SDK Tools which was really updated and I totally forgot about it. It was probably interfering with some stuff. After I have removed that Android SDK Tools version, everything went smooth. Thank you

**Comment by breautek** [comment]
Apologies for bailing, it was getting late for me last night. Glad you found your solution though!

**Comment by CLINTONPAU** [comment]
> I've ran this without the emulator started and seeing you're behavior. If I omit the `--verbose` flag, then the last thing that prints out for me is:
> 
> ```
> No emulator specified, defaulting to Nexus_5X_API_28_x86
> Waiting for emulator to start...
> PANIC: Missing emulator engine program for 'x86' CPU.
> ```
> 
> The `Running command: adb -s emulator-5554 shell ps` spam is printed after a useful error message, do you see anything like that?

Hello above you talked of starting the emulator first .. i have a question am using windows OS do you start the emulator via android studio or is there a better way to start on cordova before you run the command cordova emulate android
