### ISSUE TITLE
edit-config doesn't replace array values for UISupportedInterfaceOrientations

### ISSUE THREAD

**Issue by WuglyakBolgoink** [apache/cordova-cli#496]
# Bug Report

Related to #https://github.com/apache/cordova-ios/issues/613

### What is expected to happen?

Tag `edit-config` by using `mode="overwrite"` **MUST** replace `original` array with array from my config in `config.xml` file. 

### What does actually happen?

I try to do this change in `config.xml`:

```xml
<!-- Set orientation on iPhone -->
    <edit-config file="*-Info.plist" target="UISupportedInterfaceOrientations" mode="overwrite">
      <array>
        <string>UIInterfaceOrientationPortrait</string>
        <string>UIInterfaceOrientationPortraitUpsideDown</string>
      </array>
    </edit-config>
```

but in my `"*-Info.plist"` file I see always this:

```xml
        <key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
```

Do I something wrong? 

in documentation(https://cordova.apache.org/docs/en/latest/plugin_ref/spec.html#edit-config) was written, that we should use `mode="overwrite"` to replace a whole property with a new values... but in this case it doesn't work correct...

can you help me please?

### Command or Code

`$ cordova prepare`

### Environment, Platform, Device

macos

### Version information

```
$ cordova info

cordova-lib@9.0.1 with:
  cordova-common@3.2.0
  cordova-create@2.0.0
  cordova-fetch@2.0.1
  cordova-serve@3.0.0

Environment: 
  OS: darwin
  Node: v10.16.0
  npm: 6.9.0
```

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by raphinesse** [comment]
Please see my [explanation & workaround](https://github.com/apache/cordova-ios/issues/613#issuecomment-560923150) in #apache/cordova-ios#613. I'm going to close this issue as it duplicates that issue IMO. If you disagree, please let me know.
