### ISSUE TITLE
Cordova install fails on node v12.15

### ISSUE THREAD

**Issue by thedocbwarren** [apache/cordova-cli#500]
# Bug Report

## Problem

installing via npm causes a json parse error and fails to install

### What is expected to happen?

install of the cordova cli

### What does actually happen?

npm install -g cordova
npm ERR! Unexpected end of JSON input while parsing near '...7QR8kcp3WDvT5KEpUYMoU'

## Information

20 http fetch GET 304 https://registry.npmjs.org/update-notifier 127ms (from cache)
 28 21 http fetch GET 304 https://registry.npmjs.org/loud-rejection 128ms (from cache)
 29 22 http fetch GET 304 https://registry.npmjs.org/editor 131ms (from cache)
 30 23 silly pacote range manifest for update-notifier@^2.5.0 fetched in 130ms
 31 24 silly resolveWithNewModule update-notifier@2.5.0 checking installable status
 32 25 silly pacote range manifest for loud-rejection@^2.0.0 fetched in 132ms
 33 26 silly resolveWithNewModule loud-rejection@2.2.0 checking installable status
 34 27 silly pacote range manifest for editor@^1.0.0 fetched in 134ms
 35 28 silly resolveWithNewModule editor@1.0.0 checking installable status
 36 29 http fetch GET 304 https://registry.npmjs.org/nopt 132ms (from cache)
 37 30 silly pacote range manifest for nopt@^4.0.1 fetched in 134ms
 38 31 silly resolveWithNewModule nopt@4.0.1 checking installable status
 39 32 http fetch GET 304 https://registry.npmjs.org/cordova-lib 138ms (from cache)
 40 33 silly fetchPackageMetaData error for cordova-lib@^9.0.0 Unexpected end of JSON input while parsing near '...7QR8kcp3WDvT    5KEpUYMoU'
 41 34 http fetch GET 304 https://registry.npmjs.org/insight 141ms (from cache)
 42 35 silly pacote range manifest for insight@^0.10.1 fetched in 142ms
 43 36 silly resolveWithNewModule insight@0.10.3 checking installable status
 44 37 http fetch GET 304 https://registry.npmjs.org/cordova-common 146ms (from cache)
 45 38 silly pacote range manifest for cordova-common@^3.1.0 fetched in 155ms
 46 39 silly resolveWithNewModule cordova-common@3.2.1 checking installable status
 47 40 timing stage:rollbackFailedOptional Completed in 0ms
 48 41 timing stage:runTopLevelLifecycles Completed in 359ms
 49 42 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...7QR8kcp3WDvT5KEpUYMoU'
 50 42 verbose stack     at JSON.parse (<anonymous>)
 51 42 verbose stack     at parseJson (/Users/doctor/.nvm/versions/node/v12.15.0/lib/node_modules/npm/node_modules/json-parse-b    etter-errors/index.js:7:17)
 52 42 verbose stack     at /Users/doctor/.nvm/versions/node/v12.15.0/lib/node_modules/npm/node_modules/node-fetch-npm/src/body    .js:96:50
 53 42 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:94:5)
 54 43 verbose cwd /Users/doctor/Documents/workspace
 55 44 verbose Darwin 19.3.0
 56 45 verbose argv "/Users/doctor/.nvm/versions/node/v12.15.0/bin/node" "/Users/doctor/.nvm/versions/node/v12.15.0/bin/npm" "i    nstall" "-g" "cordova"
 57 46 verbose node v12.15.0
 58 47 verbose npm  v6.13.4
 59 48 error Unexpected end of JSON input while parsing near '...7QR8kcp3WDvT5KEpUYMoU'
 60 49 verbose exit [ 1, true ]

### Command or Code

npm install -g cordova

### Environment, Platform, Device

macOS Calalina

### Version information
Cordova version 9
node v12.15.0
macOS 10.15.3
GNU bash, version 5.0.11
xcode 11.3.1
 

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by thedocbwarren** [comment]
Let me know if more info is required.

**Comment by breautek** [comment]
This isn't a cordova issue. It looks your npm cache may be corrupted. You can try running `npm cache clean --force`
