### ISSUE TITLE
Unable to add package

### ISSUE THREAD

**Issue by rathodkaran07** [apache/cordova-cli#503]
# Bug Report

## Problem
I am unable to install cordova cli

### What is expected to happen?
Cli package should get installed

### What does actually happen?
Shows below error:

C:\Windows\System32>npm i -g cordova
npm ERR! Unexpected end of JSON input while parsing near '...t":"0.8.4","loud-reje'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Karan.Rathod\AppData\Roaming\npm-cache\_logs\2020-04-03T04_22_02_779Z-debug.log

### Version information
C:\Windows\System32>npm -v
6.13.4

C:\Windows\System32>node -v
v12.16.1

## Checklist

- [x] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by fukumotoj** [comment]
I have had similar errors occur when using nvm to swap out to different versions of node and the roaming npm cache / node_modules folder got out of sync.  Whacking the folders resolved the issue for me.

**Comment by breautek** [comment]
Closing because this isn't a cordova issue.

Appears your NPM cache is corrupted. You can try running `npm cache clear --force` or trying https://github.com/apache/cordova-cli/issues/503#issuecomment-621380260
