### ISSUE TITLE
Build error 'cannot read property startsWith of undefined' when using adaptive icons

### ISSUE THREAD

**Issue by AshleyScirra** [apache/cordova-cli#506]
# Bug Report

Sample project: 
[test.zip](https://github.com/apache/cordova-cli/files/4703578/test.zip)

Extract and run:
`cordova platform add android`
`cordova prepare android`

## Problem

It fails with `Cannot read property 'startsWith' of undefined`.

### What is expected to happen?

Successful prepare

### What does actually happen?

It fails with an error message

## Information

This only happens if you have both a normal and an adaptive icon.

### Command or Code
Included above

### Environment, Platform, Device
Windows 10 64-bit

### Version information
Cordova 9.0.0 (cordova-lib@9.0.1)

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by AshleyScirra** [comment]
Possibly related: https://github.com/ionic-team/cordova-res/issues/116

The mentioned workaround ("it looks like a workaround for this is to define the legacy icons below the adaptive icons") does not work for me. The error happens whatever order the icons come in.

**Comment by Achelys** [comment]
I'm running into the same issue when attempting to build with Adaptive Icons, and the aforementioned workaround in @AshleyScirra 's post ("it looks like a workaround for this is to define the legacy icons below the adaptive icons") doesn't work for me either. I'm on a Mac ( 10.15.6 ) with Cordova 9.0.0.

**Comment by breautek** [comment]
> I'm running into the same issue when attempting to build with Adaptive Icons, and the aforementioned workaround in @AshleyScirra 's post ("it looks like a workaround for this is to define the legacy icons below the adaptive icons") doesn't work for me either. I'm on a Mac ( 10.15.6 ) with Cordova 9.0.0.

This issue should be fixed in the latest `cordova-android` release, (currently cordova-android@9.0.0) by https://github.com/apache/cordova-android/pull/1001

If you still have an issue please open a new issue in the cordova-android repo at https://github.com/apache/cordova-android/issues

**Comment by rolinger** [comment]
@breautek - oh boy.  What can I do to resolve this while still on cordova-android@8.1 ?  I can't migrate to @9.0.0 yet as it breaks my app in a few places, and don't have time to step through it all for a while.

**Comment by breautek** [comment]
> @breautek - oh boy. What can I do to resolve this while still on cordova-android@8.1 ? I can't migrate to @9.0.0 yet as it breaks my app in a few places, and don't have time to step through it all for a while.

You can try forking `cordova-android`, branch off the `rel/8.1.0` tag and apply the https://github.com/apache/cordova-android/pull/1001 patch. Then you can install the platform over git.

`cordova platform add <https://github.com/your/cordova-android-fork#8.1.x-branch`
