### ISSUE TITLE
Cordova-Android build fails on Azure pipeline whereas the same project work perfectly fine on local build

### ISSUE THREAD

**Issue by chethanayasa** [apache/cordova-cli#509]
![image](https://user-images.githubusercontent.com/13471458/86181202-30fe1a80-baf3-11ea-87b9-23160c7b0b01.png)

This issue is not happening on local build with grunt buildAndroid only with cordova buildAndroid. Anyone know solution for this problem, I am using all updated plugin versions and platforms

![image](https://user-images.githubusercontent.com/13471458/86182898-6c4e1880-baf6-11ea-9618-edac5f5e9074.png)

Does anyone have solution for this issue?

**Comment by breautek** [comment]
Please fill out the issue form completely. It's important information for troubleshooting.

Based on the stacktrace, the issue appears to be inside `taco-team-build` package.
