### ISSUE TITLE
v1.indexOf is not a function

### ISSUE THREAD

**Issue by WuglyakBolgoink** [apache/cordova-cli#523]
Hallo guys,

I have a lot of this errors:
```
v1.indexOf is not a function
```

![image](https://user-images.githubusercontent.com/2271337/89792160-76672c00-db24-11ea-8f24-43b79370248d.png)

- node -> v14.5.0
- npm -> 6.14.5
- cordova -> 10.0.0

----

and then

```bash 
$ cordova prepare

v1.indexOf is not a function
````

**Comment by WuglyakBolgoink** [comment]
ok... I think this is not a cordova error!
possible fix is -> https://github.com/leohihimax/node-version-compare/pull/5

**Comment by breautek** [comment]
Is this still reproducible or was it fixed by https://github.com/leohihimax/node-version-compare/pull/5?

I couldn't reproduce it myself.

**Comment by WuglyakBolgoink** [comment]
Hallo @breautek, my PR(https://github.com/leohihimax/node-version-compare/pull/5) was already merged for number converting in node-version-compare package. And I think, we can close this issue now. If anyone has again problem with this, please reopen the issue again!

thank you!
