### ISSUE TITLE
No matching version found for cordova-lib@^10.0.0.

### ISSUE THREAD

**Issue by dwimarufalvansuri** [apache/cordova-cli#531]
hai, i cannot install latest cordova : 
<img width="571" alt="Screen Shot 2020-09-07 at 02 52 25" src="https://user-images.githubusercontent.com/2959401/92334135-6572f180-f0b5-11ea-94cc-819c3963aef7.png">

my nodejs version : v14.9.0

it is something i forgot to install?

thanks anyway.

**Comment by breautek** [comment]
Version `10.0.0` definitely exists on NPM... https://www.npmjs.com/package/cordova-lib/v/10.0.0

Are you using the official NPM registry?

Expected results are:

```
npm config get registry
https://registry.npmjs.org/
```

**Comment by dwimarufalvansuri** [comment]
well, you right !
its because my registry set to my private repo.
thanks a lot! :D
