### ISSUE TITLE
MacOS cordova upgrade from 9.0.0 to 10.0.0 fails

### ISSUE THREAD

**Issue by csfahey** [apache/cordova-cli#532]
### Issue Type

- [x] Bug Report
- [ ] Feature Request
- [ ] Support Question

## Description
Cordova-cli gives error message for every command after upgrading from 9.0.0 to 10.0.0 on macOS

## Information

I had a previous installation of cordova 9.0.0 installed on a mac book pro running Catalina 10.15.6 with XCode 11.2.1
installed.  While 9.0.0 was installed it displayed a message to upgrade to 10.0.0 using npm.  I ran that command.
No errors were returned during the installation.  Here is the output of running the command.

[command_output.txt](https://github.com/apache/cordova-cli/files/5189248/command_output.txt)

Here is the error after running any command:
(base) MacBook-Pro:node_modules developer$ cordova -v
/usr/local/lib/node_modules/cordova/node_modules/update-notifier/index.js:103
	async fetchInfo() {
	      ^^^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/cordova/src/cli.js:19:22)
    at Module._compile (module.js:556:32)

I also ran an update to see if it would pick up any missing elements but it only returned this:

(base) MacBook-Pro:node_modules developer$ sudo npm install -g cordova
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
/usr/local/bin/cordova -> /usr/local/lib/node_modules/cordova/bin/cordova
/usr/local/lib
└── cordova@10.0.0 

No change in the error after this.

I also uninstalled cordova, verified that it was completely uninstalled then reinstalled it but no change.

### Command or Code

sudo npm i -g cordova
cordova -v

### Environment, Platform, Device

macOS 10.15.6
MacBook Pro

### Version information

cordova cli - 10
cordova android 8.1.0
cordova io  6.1.1
xcode 11.2.1
cordova-plugin-contacts 2.0.1 "Contacts"
cordova-plugin-device 1.1.4-dev "Device"
cordova-plugin-dialogs 1.3.1-dev "Notification"
cordova-plugin-inappbrowser 4.0.0 "InAppBrowser"
cordova-plugin-splashscreen 6.0.0 "Splashscreen"
cordova-plugin-whitelist 1.2.2 "Whitelist"
cordova-support-google-services 1.3.2 "cordova-support-google-services"
es6-promise-plugin 3.0.2 "Promise"
mx.ferreyra.callnumber 0.0.2 "Cordova Call Number Plugin"
phonegap-plugin-multidex 1.0.0 "Multidex"

## Checklist

- [x] I searched for already existing GitHub issues about this
- [x] I updated all Cordova tooling to their most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
> async fetchInfo() {

This suggest you're using an unsupported version of Node. The minimum supported node in Cordova10 is Node 10.

Use `node -v` to determine what version of NodeJS you're using.

**Comment by timbru31** [comment]
Closing due to lack of feedback and a solution from Norman. Note that you actually need Node.js v10.10 or greater for Android.

**Comment by csfahey** [comment]
Thanks guys
