### ISSUE TITLE
Preparing platform fails to install cordova plugin from local folder in node 15

### ISSUE THREAD

**Issue by vanessag** [apache/cordova-cli#541]
# Bug Report

## Problem
I am using ionic with node 15 and when I start with a fresh install of my project via `ionic cordova prepare ios` I am getting this error when attempting to install a local cordova plugin:

> Failed to fetch plugin file:path/to/file via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
CordovaError: CordovaError: Could not determine package name from output:

### What is expected to happen?
Expected local plugin to install correctly.

### What does actually happen?
Local plugin fails to install.

## Information
Attempt to add a cordova plugin from a local folder to an ionic project. I am only able to receive this error on node version 15. This error does not occur with node version 14.

`ionic cordova plugin add file:/path/to/file --verbose`

Will receive error message:

> CordovaError: Failed to fetch plugin file:/path/to/file via registry.
> Probably this is either a connection problem, or plugin spec is incorrect.
> Check your connection and plugin name/version/URL.
> CordovaError: CordovaError: Could not determine package name from output:
> up to date, audited 1596 packages in 3s

> found 0 vulnerabilities
>     at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:140:43
>     at processTicksAndRejections (node:internal/process/task_queues:93:5)
> [ERROR] An error occurred while running subprocess cordova.

### Command or Code
`ionic cordova prepare ios --verbose`

`ionic cordova plugin add file:/path/to/file --verbose`

### Environment, Platform, Device
Mac OS Catalina Version 10.15.7

### Version information

Ionic:

   Ionic CLI                     : 6.12.2 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.5.0
   @angular-devkit/build-angular : 0.1100.2
   @angular-devkit/schematics    : 11.0.2
   @angular/cli                  : 11.0.2
   @ionic/angular-toolkit        : 3.0.0

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 9.0.0, ios 6.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 6 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 1.2.2

System:

   Android SDK Tools : 26.1.1 (/Users/vanessa/Library/Android/sdk)
   ios-deploy        : 1.11.3
   ios-sim           : ios-sim/9.0.0 darwin-x64 node-v15.2.1
   NodeJS            : v15.2.1 (/usr/local/Cellar/node/15.2.1/bin/node)
   npm               : 7.0.10
   OS                : macOS Catalina
   Xcode             : Xcode 12.2 Build version 12B45b

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by dpogue** [comment]
There are issues with Cordova and npm v7 (which is included in node v15): https://github.com/apache/cordova-lib/issues/859
We're aware and working on getting them fixed before node 16 goes stable.

In the meantime, if you're using node v15, you can `npm install -g npm` to downgrade npm to the stable (v6) release.
