### ISSUE TITLE
Cordova is throwing unexpected error while creating the app

### ISSUE THREAD

**Issue by omvaishnav** [apache/cordova-cli#542]
# Bug Report

## Problem
![image](https://user-images.githubusercontent.com/760149/100181033-66226380-2eff-11eb-952e-587dce460d5a.png)
Not able to create my first cordova app because of the above error.

### What is expected to happen?
Should create my first app with the command

### What does actually happen?
cordova is throwing error even if I just run "cordova" in cmd after globally installed.

## Information

I have attached the screenshot above.

### Command or Code

I ran the follwing command to create the app
cordova create myApp com.example.myApp myApp

### Environment, Platform, Device

OS: Windows10

### Version information

NPM: 6.1.0
Cordova: 10.0.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by raphinesse** [comment]
My guess would be that your version of Node.js is too old. Please install one of the [currently supported versions](https://nodejs.org/en/about/releases/). I suggest v14.

**Comment by omvaishnav** [comment]
It's working after updating NPM. Thanks @raphinesse
