### ISSUE TITLE
window.ResizeObserver is undefined in iOS

### ISSUE THREAD

**Issue by sylvestrevgen** [apache/cordova-cli#556]
# Bug Report

## Problem
window.ResizeObserver is undefined in iOS.

### What is expected to happen?
window.ResizeObserver is defined in both platforms - Android and iOS.

### What does actually happen?
window.ResizeObserver is undefined in iOS. In Android everything is fine.

### Version information

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by dpogue** [comment]
`ResizeObserver` is [only supported on iOS 13.7 and newer](https://caniuse.com/resizeobserver).

Cordova relies on the system webview capabilities and is not responsible for implementing web APIs itself.
