### ISSUE TITLE
Should `cordova plugin save` be removed/updated?

### ISSUE THREAD

**Issue by matt-auckland** [apache/cordova-cli#558]
# Feature Request

Note: I'm happy to help implement this feature myself if it's deemed worthy of implementation

Either remove the feature straight up, or perhaps running it could update the `package.json` instead of the config.xml?

We could start by deprecating if removal is the option of choice.

## Motivation Behind Feature
`cordova plugin save` add the currently installed plugins into the `config.xml` as `<plugin>` elements.

Since the cordova CLI no longer looks to the `config.xml` for plugin information, perhaps it's time for this command to be repurposed or removed altogether?

**Comment by raphinesse** [comment]
Thanks for bringing this to our attention. Since we save the list of installed plugins to configuration files by default for quite some time now, I would argue we should remove that command altogether.

**Comment by matt-auckland** [comment]
Looks like it's already been removed from `cordova-lib` here: https://github.com/apache/cordova-lib/pull/781 .
It's also been removed from the cli here as well: https://github.com/apache/cordova-cli/pull/486

All that remains is that it appears when you run `cordova plugin --help`, so removing that here: https://github.com/apache/cordova-cli/pull/559
