### ISSUE TITLE
[ERROR] An error occurred while running subprocess cordova.

### ISSUE THREAD

**Issue by carlo1010** [apache/cordova-cli#562]
myd82ta@MacBook-Pro-di-Fanny mobile % ionic cordova platform add ios --verbose
  ionic:lib Terminal info: { ci: false, shell: '/bin/zsh', tty: true, windows: false } +0ms
  ionic:lib CLI global options: { _: [ 'cordova', 'platform', 'add', 'ios' ], help: null, h: null, verbose: true, quiet: null, interactive: true, color: true, confirm: null, json: null, project: null, '--': [] } +3ms
  ionic:lib:project Project type from config: @ionic/angular (angular) +0ms
  ionic:lib:project Project details: { context: 'app', type: 'angular', errors: [], configPath: '/Users/myd82ta/Documents/mobile/ionic.config.json' } +1ms
  ionic Context: { binPath: '/usr/local/lib/node_modules/@ionic/cli/bin/ionic', libPath: '/usr/local/lib/node_modules/@ionic/cli', execPath: '/Users/myd82ta/Documents/mobile', version: '6.16.3' } +0ms
  ionic:lib:integrations:cordova:config Loading Cordova Config (config.xml: '/Users/myd82ta/Documents/mobile/config.xml', package.json: '/Users/myd82ta/Documents/mobile/package.json') +0ms
  ionic:lib:telemetry Sending telemetry for command: 'ionic cordova platform' [ 'add', 'ios', '--verbose', '--interactive', '--color' ] +0ms
> cordova platform add ios --verbose
No scripts found for hook "before_platform_add".
No version supplied. Retrieving version from config.xml...
Grabbing pinned version.
Using cordova-fetch for cordova-ios@^6.1.0
fetch: Installing cordova-ios@^6.1.0 to /Users/myd82ta/Documents/mobile
Running command: npm install cordova-ios@^6.1.0 --save-dev
Command finished with error code 0: npm install,cordova-ios@^6.1.0,--save-dev
Removing "cordova-" prefix from cordova-ios
Adding ios project...
Platform API successfully found in: /Users/myd82ta/Documents/mobile/node_modules/cordova-ios
Creating Cordova project for the iOS platform:
	Path: platforms/ios
	Package: com.piccosoft.spurtcommerce
	Name: Gruppo Piccirillo
Copying iOS template project to /Users/myd82ta/Documents/mobile/platforms/ios
iOS project created with cordova-ios@6.2.0
Platform API successfully found in: /Users/myd82ta/Documents/mobile/platforms/ios/cordova/Api.js
Generating platform-specific config.xml from defaults for iOS at /Users/myd82ta/Documents/mobile/platforms/ios/Gruppo Piccirillo/config.xml
Merging project's config.xml into platform-specific iOS config.xml
Merging and updating files from [www, platforms/ios/platform_www] to platforms/ios/www
  mkdir platforms/ios/www/cordova-js-src
  copy  platforms/ios/platform_www/cordova-js-src/exec.js platforms/ios/www/cordova-js-src/exec.js (new file)
  copy  platforms/ios/platform_www/cordova-js-src/platform.js platforms/ios/www/cordova-js-src/platform.js (new file)
  mkdir platforms/ios/www/cordova-js-src/plugin
  mkdir platforms/ios/www/cordova-js-src/plugin/ios
  copy  platforms/ios/platform_www/cordova-js-src/plugin/ios/console.js platforms/ios/www/cordova-js-src/plugin/ios/console.js (new file)
  copy  platforms/ios/platform_www/cordova-js-src/plugin/ios/launchscreen.js platforms/ios/www/cordova-js-src/plugin/ios/launchscreen.js (new file)
  copy  platforms/ios/platform_www/cordova-js-src/plugin/ios/logger.js platforms/ios/www/cordova-js-src/plugin/ios/logger.js (new file)
  copy  platforms/ios/platform_www/cordova-js-src/plugin/ios/wkwebkit.js platforms/ios/www/cordova-js-src/plugin/ios/wkwebkit.js (new file)
  copy  platforms/ios/platform_www/cordova.js platforms/ios/www/cordova.js (updated file)
  delete platforms/ios/www/css (no source)
  delete platforms/ios/www/css/index.css (no source)
  delete platforms/ios/www/img (no source)
  delete platforms/ios/www/img/logo.png (no source)
  delete platforms/ios/www/index.html (no source)
  delete platforms/ios/www/js (no source)
  delete platforms/ios/www/js/index.js (no source)
Wrote out iOS Bundle Version "0.0.1" to /Users/myd82ta/Documents/mobile/platforms/ios/Gruppo Piccirillo/Gruppo Piccirillo-Info.plist
Set PRODUCT_BUNDLE_IDENTIFIER to com.piccosoft.spurtcommerce.
iOS Product Name has not changed (still "Gruppo Piccirillo")
Updating icons at platforms/ios/Gruppo Piccirillo/Images.xcassets/AppIcon.appiconset/
  copy  resources/ios/icon/icon-1024.png platforms/ios/Gruppo Piccirillo/Images.xcassets/AppIcon.appiconset/icon-1024.png (updated file)
  copy  resources/ios/icon/icon-20.png platforms/ios/Gruppo Piccirillo/Images.xcassets/AppIcon.appiconset/icon-20.png (updated file)
  copy  resources/ios/icon/icon-20@2x.png platforms/ios/Gruppo Piccirillo/Images.xcassets/AppIcon.appiconset/icon-20@2x.png (updated file)
  copy  resources/ios/icon/icon-20@3x.png platforms/ios/Gruppo Piccirillo/Images.xcassets/AppIcon.appiconset/icon-20@3x.png (updated file)
  copy  resources/ios/icon/icon-24@2x.png platforms/ios/Gruppo Piccirillo/Images.xcassets/AppIcon.appiconset/icon-24@2x.png (updated file)
  copy  resources/ios/icon/icon-27.5@2x.png platforms/ios/Gruppo Piccirillo/Images.xcassets/AppIcon.appiconset/icon-27.5@2x.png (updated file)
  copy  resources/ios/icon/icon-small.png platforms/ios/Gruppo Piccirillo/Images.xcassets/AppIcon.appiconset/icon-29.png (updated file)
  copy  resources/ios/icon/icon-small@2x.png platforms/ios/Gruppo Piccirillo/Images.xcassets/AppIcon.appiconset/icon-29@2x.png (updated file)
  copy  resources/ios/icon/icon-small@3x.png platforms/ios/Gruppo Piccirillo/Images.xcassets/AppIcon.appiconset/icon-29@3x.png (updated file)
  copy  resources/ios/icon/icon-20@2x.png platforms/ios/Gruppo Piccirillo/Images.xcassets/AppIcon.appiconset/icon-40.png (updated file)
  copy  resources/ios/icon/icon-40@2x.png platforms/ios/Gruppo Piccirillo/Images.xcassets/AppIcon.appiconset/icon-40@2x.png (updated file)
  copy  resources/ios/icon/icon-44@2x.png platforms/ios/Gruppo Piccirillo/Images.xcassets/AppIcon.appiconset/icon-44@2x.png (updated file)
  copy  resources/ios/icon/icon-50.png platforms/ios/Gruppo Piccirillo/Images.xcassets/AppIcon.appiconset/icon-50.png (updated file)
  copy  resources/ios/icon/icon-50@2x.png platforms/ios/Gruppo Piccirillo/Images.xcassets/AppIcon.appiconset/icon-50@2x.png (updated file)
  copy  resources/ios/icon/icon-40@3x.png platforms/ios/Gruppo Piccirillo/Images.xcassets/AppIcon.appiconset/icon-60@2x.png (updated file)
  copy  resources/ios/icon/icon-60@3x.png platforms/ios/Gruppo Piccirillo/Images.xcassets/AppIcon.appiconset/icon-60@3x.png (updated file)
  copy  resources/ios/icon/icon-72.png platforms/ios/Gruppo Piccirillo/Images.xcassets/AppIcon.appiconset/icon-72.png (updated file)
  copy  resources/ios/icon/icon-72@2x.png platforms/ios/Gruppo Piccirillo/Images.xcassets/AppIcon.appiconset/icon-72@2x.png (updated file)
  copy  resources/ios/icon/icon-76.png platforms/ios/Gruppo Piccirillo/Images.xcassets/AppIcon.appiconset/icon-76.png (updated file)
  copy  resources/ios/icon/icon-76@2x.png platforms/ios/Gruppo Piccirillo/Images.xcassets/AppIcon.appiconset/icon-76@2x.png (updated file)
  copy  resources/ios/icon/icon-83.5@2x.png platforms/ios/Gruppo Piccirillo/Images.xcassets/AppIcon.appiconset/icon-83.5@2x.png (updated file)
  copy  resources/ios/icon/icon-86@2x.png platforms/ios/Gruppo Piccirillo/Images.xcassets/AppIcon.appiconset/icon-86@2x.png (updated file)
  copy  resources/ios/icon/icon-98@2x.png platforms/ios/Gruppo Piccirillo/Images.xcassets/AppIcon.appiconset/icon-98@2x.png (updated file)
  copy  resources/ios/icon/icon.png platforms/ios/Gruppo Piccirillo/Images.xcassets/AppIcon.appiconset/icon.png (updated file)
  copy  resources/ios/icon/icon@2x.png platforms/ios/Gruppo Piccirillo/Images.xcassets/AppIcon.appiconset/icon@2x.png (updated file)
Updating launch storyboard images at platforms/ios/Gruppo Piccirillo/Images.xcassets/LaunchStoryboard.imageset/
  copy  resources/ios/splash/Default@2x~universal~anyany.png platforms/ios/Gruppo Piccirillo/Images.xcassets/LaunchStoryboard.imageset/Default@2x~universal~anyany.png (new file)
Updating Storyboard image set contents.json
Updating Background Color color set Contents.json
This app does not have additional resource files defined
Prepared iOS project successfully
Installing plugin "com.razorpay.cordova" following successful platform add of ios
Found variables for "com.razorpay.cordova". Processing as cli_variables.
Installing "com.razorpay.cordova" for ios
Finding scripts for "before_plugin_install" hook from plugin com.razorpay.cordova on ios platform only.
No scripts found for hook "before_plugin_install".
Install start for "com.razorpay.cordova" on ios.
Beginning processing of action stack for ios project...
Adding custom framework to project... src/ios/Razorpay.framework -> {"customFramework":true,"embed":false,"link":true,"sign":true}
Custom framework added to project. src/ios/Razorpay.framework -> {"customFramework":true,"link":true,"sign":true}
Adding non-custom framework to project... CoreTelephony.framework -> {"customFramework":false,"embed":false,"link":true,"weak":false}
Non-custom framework added to project. CoreTelephony.framework -> {"customFramework":false,"link":true,"weak":false}
Adding non-custom framework to project... SystemConfiguration.framework -> {"customFramework":false,"embed":false,"link":true,"weak":false}
Non-custom framework added to project. SystemConfiguration.framework -> {"customFramework":false,"link":true,"weak":false}
Action stack processing complete.
pods.json: The file at /Users/myd82ta/Documents/mobile/platforms/ios/pods.json does not exist.
Creating new pods.json in platforms/ios
Wrote to pods.json.
Podfile: The file at /Users/myd82ta/Documents/mobile/platforms/ios/Podfile does not exist.
Creating new Podfile in platforms/ios
Wrote to Podfile.
Install complete for com.razorpay.cordova on ios.
Finding scripts for "after_plugin_install" hook from plugin com.razorpay.cordova on ios platform only.
No scripts found for hook "after_plugin_install".
Installing plugin "cordova-plugin-camera" following successful platform add of ios
Found variables for "cordova-plugin-camera". Processing as cli_variables.
Installing "cordova-plugin-camera" for ios
Finding scripts for "before_plugin_install" hook from plugin cordova-plugin-camera on ios platform only.
No scripts found for hook "before_plugin_install".
Install start for "cordova-plugin-camera" on ios.
Beginning processing of action stack for ios project...
Adding non-custom framework to project... ImageIO.framework -> {"customFramework":false,"embed":false,"link":true,"weak":true}
Non-custom framework added to project. ImageIO.framework -> {"customFramework":false,"link":true,"weak":true}
Adding non-custom framework to project... CoreLocation.framework -> {"customFramework":false,"embed":false,"link":true,"weak":false}
Non-custom framework added to project. CoreLocation.framework -> {"customFramework":false,"link":true,"weak":false}
Adding non-custom framework to project... AVFoundation.framework -> {"customFramework":false,"embed":false,"link":true,"weak":false}
Non-custom framework added to project. AVFoundation.framework -> {"customFramework":false,"link":true,"weak":false}
Action stack processing complete.
pods.json found in platforms/ios
Podfile found in platforms/ios
Install complete for cordova-plugin-camera on ios.
Finding scripts for "after_plugin_install" hook from plugin cordova-plugin-camera on ios platform only.
No scripts found for hook "after_plugin_install".
Installing plugin "cordova-plugin-device" following successful platform add of ios
Found variables for "cordova-plugin-device". Processing as cli_variables.
Installing "cordova-plugin-device" for ios
Finding scripts for "before_plugin_install" hook from plugin cordova-plugin-device on ios platform only.
No scripts found for hook "before_plugin_install".
Install start for "cordova-plugin-device" on ios.
Beginning processing of action stack for ios project...
Action stack processing complete.
pods.json found in platforms/ios
Podfile found in platforms/ios
Install complete for cordova-plugin-device on ios.
Finding scripts for "after_plugin_install" hook from plugin cordova-plugin-device on ios platform only.
No scripts found for hook "after_plugin_install".
Installing plugin "cordova-plugin-facebook4" following successful platform add of ios
Found variables for "cordova-plugin-facebook4". Processing as cli_variables.
Installing "cordova-plugin-facebook4" for ios
Finding scripts for "before_plugin_install" hook from plugin cordova-plugin-facebook4 on ios platform only.
No scripts found for hook "before_plugin_install".
Install start for "cordova-plugin-facebook4" on ios.
Beginning processing of action stack for ios project...
Action stack processing complete.
pods.json found in platforms/ios
Podfile found in platforms/ios
Adding pods since the plugin contained <podspecs>
Set pods.json for `declarations` - `use_frameworks!`
Added declaration line for `use_frameworks!`
Set pods.json for `sources` - `https://cdn.cocoapods.org/`
Added source line for `https://cdn.cocoapods.org/`
Set pods.json for `libraries` - `FBSDKCoreKit`
Added pod line for `FBSDKCoreKit`
Set pods.json for `libraries` - `FBSDKLoginKit`
Added pod line for `FBSDKLoginKit`
Set pods.json for `libraries` - `FBSDKShareKit`
Added pod line for `FBSDKShareKit`
Wrote to pods.json.
Wrote to Podfile.
Running `pod install` (to install plugins)
Failed to install 'cordova-plugin-facebook4': CordovaError: CocoaPods was not found. Please install version 1.8.0 or greater from https://cocoapods.org/
    at checkTool (/Users/myd82ta/Documents/mobile/platforms/ios/cordova/lib/check_reqs.js:95:31)
    at module.exports.check_cocoapods (/Users/myd82ta/Documents/mobile/platforms/ios/cordova/lib/check_reqs.js:72:16)
    at Podfile.install (/Users/myd82ta/Documents/mobile/platforms/ios/cordova/lib/Podfile.js:392:12)
    at Api.addPodSpecs (/Users/myd82ta/Documents/mobile/platforms/ios/cordova/Api.js:451:32)
    at /Users/myd82ta/Documents/mobile/platforms/ios/cordova/Api.js:278:29
    at _fulfilled (/Users/myd82ta/Documents/mobile/node_modules/q/q.js:854:54)
    at /Users/myd82ta/Documents/mobile/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/Users/myd82ta/Documents/mobile/node_modules/q/q.js:816:13)
    at /Users/myd82ta/Documents/mobile/node_modules/q/q.js:624:44
    at runSingle (/Users/myd82ta/Documents/mobile/node_modules/q/q.js:137:13)
CocoaPods was not found. Please install version 1.8.0 or greater from https://cocoapods.org/
CordovaError: CocoaPods was not found. Please install version 1.8.0 or greater from https://cocoapods.org/
    at checkTool (/Users/myd82ta/Documents/mobile/platforms/ios/cordova/lib/check_reqs.js:95:31)
    at module.exports.check_cocoapods (/Users/myd82ta/Documents/mobile/platforms/ios/cordova/lib/check_reqs.js:72:16)
    at Podfile.install (/Users/myd82ta/Documents/mobile/platforms/ios/cordova/lib/Podfile.js:392:12)
    at Api.addPodSpecs (/Users/myd82ta/Documents/mobile/platforms/ios/cordova/Api.js:451:32)
    at /Users/myd82ta/Documents/mobile/platforms/ios/cordova/Api.js:278:29
    at _fulfilled (/Users/myd82ta/Documents/mobile/node_modules/q/q.js:854:54)
    at /Users/myd82ta/Documents/mobile/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/Users/myd82ta/Documents/mobile/node_modules/q/q.js:816:13)
    at /Users/myd82ta/Documents/mobile/node_modules/q/q.js:624:44
    at runSingle (/Users/myd82ta/Documents/mobile/node_modules/q/q.js:137:13)
[ERROR] An error occurred while running subprocess cordova.
        
        cordova platform add ios --verbose exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more information.
  ionic:utils-process onBeforeExit handler: 'process.exit' received +0ms
  ionic:utils-process onBeforeExit handler: running 1 functions +0ms
  ionic:utils-process processExit: exiting (exit code: 1) +26ms

**Comment by breautek** [comment]
> Failed to install 'cordova-plugin-facebook4': CordovaError: CocoaPods was not found. Please install version 1.8.0 or greater from https://cocoapods.org/

I'm not really sure how to make this error message any more clear. Closing this as invalid.
