### ISSUE TITLE
Why require variables to remove a plugin?

### ISSUE THREAD

**Issue by SteveKennedy** [apache/cordova-cli#568]
When I want to install a plugin, I use this format:

_cordova plugin add cordova-plugin-xxxx --variable APP_ID="123456789" --variable APP_NAME="Really Cool AppName"_

When I go to remove this plugin, why must I also supply the exact same variables? I would think that I could remove the plugin using simply:

_cordova plugin rm cordova-plugin-xxxx_

**Comment by erisu** [comment]
I will be closing out this issue because it is a duplicate of #446.
