### ISSUE TITLE
Cordova CLI 11 : Plugin and Platforms Not Save in config.xml

### ISSUE THREAD

**Issue by JLWINC** [apache/cordova-cli#577]
I upgraded my **CORDOVA CLI** version from **8** to **11** , when i try to add a new **plugin** or **platform** nothing save in **config.xml** i try to add **--save** but nothing added , and in **android** is not generate the icon and splash screen config !!

 i miss something ?

Thanks.

**Comment by dpogue** [comment]
When you add platforms and plugins, they should be saved to package.json in newer versions of Cordova.

**Comment by JLWINC** [comment]
ok thank you , 
and the Adaptive Icon for **android** where is its the location when i run` cordova platform add android` nothing  saved to **config.xml** like the old version or i should to added manuelle ??

```
<platform name="android">
  <icon background="res/icon/android/ldpi-background.png" density="ldpi" foreground="res/icon/android/ldpi-foreground.png" />
  <icon background="res/icon/android/mdpi-background.png" density="mdpi" foreground="res/icon/android/mdpi-foreground.png" />
  <icon background="res/icon/android/hdpi-background.png" density="hdpi" foreground="res/icon/android/hdpi-foreground.png" />
  <icon background="res/icon/android/xhdpi-background.png" density="xhdpi" foreground="res/icon/android/xhdpi-foreground.png" />
  <icon background="res/icon/android/xxhdpi-background.png" density="xxhdpi" foreground="res/icon/android/xxhdpi-foreground.png" />
  <icon background="res/icon/android/xxxhdpi-background.png" density="xxxhdpi" foreground="res/icon/android/xxxhdpi-foreground.png" />
</platform>

```
