### ISSUE TITLE
Updation of transitive dependency got@9.6.0 to version greater than 12.1.0

### ISSUE THREAD

**Issue by ashmeetkb** [apache/cordova-cli#585]
Feature Request:
Cordova in its latest version 11.0.0 transitively depends on got@9.6.0. Please upgrade the transitive dependency 'got@9.6.0' to a version greater than 12.1.0 in the newer releases of cordova.

Motivation Behind Feature: Mend (formerly WhiteSource) reports got-9.6.0.tgz as a vulnerability having CVSS 3 score: 5.3, since the got package before 12.1.0 (also fixed in 11.8.5) for Node.js allows a redirect to a UNIX socket. 

Feature Description: Newer versions of cordova to have a transitive dependency on 'got' version greater than 12.1.0 instead of the current 9.6.0 version.

**Comment by breautek** [comment]
Had a quick glance at this and this will require some work.

Our direct dependency that `got` comes from is `update-notifier` and we need to update to `6.0.2` which is a [breaking change](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c).

Version 6 is pure esm, which means you cannot directly require it via NodeJS `require`. It requires the use of ESM modules via `import` syntax.

This means to continue using `update-notifer` we need to convert Cordova to be ESM.

**Comment by ashmeetkb** [comment]
Okay. Can you please share a rough estimate of when can we expect this change, since, for our project, got-9.6.0.tgz is a vulnerability having CVSS 3 score: 5.3 as a part of our WhiteSource (now MEND) Scan that needs to be addressed?

**Comment by erisu** [comment]
Resolved in https://github.com/apache/cordova-cli/pull/595
