### ISSUE TITLE
Update the macos-release package to 3.1.0 to include macos 13

### ISSUE THREAD

**Issue by UlricW** [apache/cordova-cli#604]
# Bug Report
The macos-release version doesn't contains the last macos version 13 Ventura
## Problem
The cordova command failed directly because the macos version doesn't exist in the package macos-release

### What is expected to happen?
The cordova command is well executed

### What does actually happen?
The cordova command crash (even for cordova -v) 

### Environment, Platform, Device

Cordova 11.1.0
Macos 13

**Comment by breautek** [comment]
duplicate: https://github.com/apache/cordova-cli/issues/589

In summary, `macos-release` is a chlid dependency of `insight`, which is our direct dependency. `insight` doesn't appear to be maintained anymore, but even if it was, updating `macos-release` isn't very feasible as it is a pure ESM package now, which is not compatible with CJS packages. Only ESM style packages can import ESM-style code.

So in order for Cordova to use it, we would have to migrate the entire codebase to ESM which is quite a daunting task.
