### ISSUE TITLE
Build failing when edit-config tag is added to config.xml

### ISSUE THREAD

**Issue by ajprok** [apache/cordova-cli#607]
# Bug Report
Build failing when edit-config tag is added to config.xml, and running `cordova build`

## Problem
On adding the following to config.xml of a freshly installed cordova project:
```
<platform name="android">
    <edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest">
        <!-- Add app install location preference - internal or external storage -->
        <manifest android:installLocation="auto" />
    </edit-config>
</platform>
```

The following error occurs in CLI:
```
Command failed with exit code 1: /home/ajit/current-projects/lap/lap-frontend/platforms/android/gradlew cdvBuildDebug -b /home/ajit/current-projects/lap/lap-frontend/platforms/android/build.gradle
Error: Command failed with exit code 1: /home/ajit/current-projects/lap/lap-frontend/platforms/android/gradlew cdvBuildDebug -b /home/ajit/current-projects/lap/lap-frontend/platforms/android/build.gradle
    at makeError (/home/ajit/current-projects/lap/lap-frontend/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/home/ajit/current-projects/lap/lap-frontend/node_modules/execa/index.js:118:26)                                                                                  
    at processTicksAndRejections (node:internal/process/task_queues:96:5)                                                                                                               
    at async ProjectBuilder.build (/home/ajit/current-projects/lap/lap-frontend/node_modules/cordova-android/lib/builders/ProjectBuilder.js:316:20)
```

This is the error that Android Studio shows on building:
```
ParseError at [row,col]:[17,52]
Message: http://www.w3.org/TR/1999/REC-xml-names-19990114#AttributePrefixUnbound?manifest&android:installLocation&android
```

**Please note, the AndroidManifest.xml file is updated properly.**

### What is expected to happen?
Should build without any issues

### What does actually happen?
As mentioned in problem section

## Information

cordova version: 11.1.0
node version: v16.18.0
java version:
```
java 11.0.14 2022-01-18 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.14+8-LTS-263)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.14+8-LTS-263, mixed mode)
```

Please let me know if you require any more information.

### Command or Code

cordova build

### Environment, Platform, Device

OS: Lubuntu, Platform: Linux, Device: Acer laptop

## Checklist

- [ x] I searched for existing GitHub issues
- [ x] I updated all Cordova tooling to most recent version
- [ x] I included all the necessary information above

**Comment by dpogue** [comment]
You need to add `xmlns:android="http://schemas.android.com/apk/res/android"` to your `<widget>` tag in config.xml.

The entire config.xml tag must be valid XML, which means any namespaces used in `edit-config` or `config-file` need to be declared.
