### ISSUE TITLE
Supporting Windows Platform

### ISSUE THREAD

**Issue by nzionisf** [apache/cordova-cli#628]
Hi
I'm using the Windows Platform although it is deprecated - so for that I'm still using the Cordova CLI 11.1.0 
Do you know if the 11.1.0 version could be deprecated or just stop working? for example, if I'll use a new node version or any other new dependency like the dependencies here?
https://github.com/apache/cordova-cli/commit/93bcae0736779058fe805a5c142b3fe764b04415

Thanks

**Comment by breautek** [comment]
We don't test for platforms that have been sunset and/or deprecated. The CLI is fairly decoupled from the actual platform, so it might work, but it might not work.

Either way we won't be addressing issues regarding the cordova-windows platform.
